version: "3.9"

services:
  frontend:
    build:
      context: ./softheal
    ports:
      - "8080:80" 
    restart: always

  backend:
    build:
      context: ./softheal-drf
    ports:
      - "8000:8000" 
    restart: always

